meta_name: "Barocentre"
meta_title: "Barocenter - Mets tes potes d'accord"
meta_description: "Crée des événements et invite tes copains pour trouver le meilleur bar où se retrouver"
meta_image: "barocentre.jpg" # should exist in `app/assets/images/`
